# Generated by Django 3.1.3 on 2020-12-08 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('user_email', models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=70, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='kaziapp.user')),
                ('profile_pic', models.ImageField(default='default.png', upload_to='image/')),
                ('bio', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('company', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('applicants', models.CharField(choices=[('EMPLOYER', 'employer'), ('EMPLOYEE', 'employee')], max_length=20)),
                ('job', models.CharField(max_length=50, null=True)),
                ('descriptions', models.TextField(max_length=200, null=True)),
                ('pay', models.PositiveIntegerField()),
                ('picture', models.ImageField(default='default.jpg', upload_to='avatar/')),
                ('post', tinymce.models.HTMLField(null=True)),
                ('contact', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
